
export const data = [
    {
        id: 0,
        product_name: "Max Men Solid Crew Neck Lounge T-Shirt",
        price: 289,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product1-300x300",
        productNumber: 1,
        rating: 4,
    },
    {
        id: 1,
        product_name: "T-Max Men Solid Crew Neck Lounge T-Shirt",
        price: 149,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product2-300x300.png",
        productNumber: 1,
        rating: 3,
    },
    {
        id: 2,
        product_name: "Allen Solly Men's Regular Fit Polo",
        price: 299,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product3-300x300.png",
        productNumber: 1,
        rating: 3.5,
    },
    {
        id: 3,
        product_name: "Max Men Textured Slim Fit Structured T-Shirt",
        price: 299,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product4-300x300.png",
        productNumber: 1,
        rating: 4.3,
    },
    {
        id: 4,
        product_name: "Lavie Women's Oval Frame Clutch | Ladies Purse Wallet",
        price: 899,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product5.png",
        productNumber: 1,
        rating: 4.5,
    },
    {
        id: 5,
        product_name: "AUSHA® 16MP 4K HD Digital Action Camera Supports HDMI",
        price: 2635,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product6.png",
        productNumber: 1,
        rating: 5,
    },
    {
        id: 6,
        product_name: "Sonata Analog Women's Watch",
        price: 610,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product7.png",
        productNumber: 1,
        rating: 4.1
    },
    {
        id: 7,
        product_name: "Max Men Solid Crew Neck Lounge T-Shirt",
        price: 349,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product1-300x300.png",
        productNumber: 1,
        rating: 4.8,
    },
    
]